### ISSUE TITLE
Fix missing dependencies

### ISSUE THREAD

**Issue by audreyrain** [TaxIPP-Life/til-france#22]
The `til_init`scripts depends on:
 - ipp_macro_series_parser
 - openfisca-survey-manager

**Comment by benjello** [comment]
Fixed by https://github.com/TaxIPP-Life/til-france/commit/1e38c37d2dd86388c5a74e0798691206d501fa17
and https://github.com/TaxIPP-Life/til-france/commit/e11198ed181e749bc0b6e5bb30de55bb4e9ed939
